import type { StorePageContent } from "@/components/store/types";

export const storePageContent: Record<"it" | "en", StorePageContent> = {
  it: {
    allProductsLabel: "Tutti",
    discountsLabel: "Sconti",
    resultsLabel: "prodotti",
    emptyLabel: "Nessun prodotto disponibile per questo filtro.",
    addToCartLabel: "Aggiungi al carrello",
    addedToCartLabel: "Aggiunto al carrello",
    openProductLabel: "Apri prodotto",
    backToStoreLabel: "Torna allo store",
    detailLabel: "Descrizione completa",
    cartTitle: "Carrello",
    emptyCartLabel: "Il carrello è vuoto.",
    checkoutLabel: "Procedi al pagamento",
    quantityLabel: "Qta",
    totalLabel: "Totale",
    cartAriaLabel: "Apri il carrello",
    removeFromCartLabel: "Rimuovi",
    checkoutTitle: "Checkout",
    checkoutEmptyLabel: "Aggiungi prodotti al carrello per procedere.",
    sortLabel: "Ordina per",
    filterLabel: "Filtra per",
    sortOptions: {
      priceAsc: "Prezzo crescente",
      priceDesc: "Prezzo decrescente",
      nameAsc: "Nome A-Z",
    },
    categories: ["Abbigliamento", "Accessori", "Attrezzatura", "Mascotte"],
    products: [
      {
        id: "SP01",
        slug: "breda-2026-team-backpack",
        category: "Accessori",
        name: "Breda 2026 Team Backpack",
        amountCents: 6400,
        price: "EUR 64,00",
        isDiscounted: false,
        shortDescription:
          "Zaino ufficiale Breda 2026 pensato per allenamenti, trasferte e uso quotidiano, con identità grafica coordinata.",
        fullDescription: [
          "Breda 2026 Team Backpack è lo zaino ufficiale della collezione sportiva, progettato per accompagnare atleti e supporter tra campo, viaggio e tempo libero.",
          "Il formato è pensato per organizzare l'essenziale da allenamento mantenendo una presenza visiva pulita e immediatamente riconoscibile.",
          "La grafica coordinata Breda 2026 lo rende adatto anche a team kit, attività promozionali e gifting sportivo.",
        ],
        imageSrc: "/Breda2026_Merch/BackPack.png",
        imageAlt: "Zaino ufficiale Breda 2026",
      },
      {
        id: "SP02",
        slug: "breda-2026-team-cap",
        category: "Accessori",
        name: "Breda 2026 Team Cap",
        amountCents: 2800,
        price: "EUR 28,00",
        isDiscounted: true,
        shortDescription:
          "Cappellino ufficiale della collezione Breda 2026, ideale per eventi, match day e attività outdoor.",
        fullDescription: [
          "Breda 2026 Team Cap completa il look ufficiale della collezione con un accessorio leggero e versatile.",
          "È pensato per accompagnare pubblico, staff e squadra durante eventi, giornate sportive e momenti informali.",
          "Il design coordinato lo rende una referenza immediata per merchandising, fan engagement e kit evento.",
        ],
        imageSrc: "/Breda2026_Merch/Cap.png",
        imageAlt: "Cappellino ufficiale Breda 2026",
      },
      {
        id: "SP03",
        slug: "breda-2026-sport-harness",
        category: "Attrezzatura",
        name: "Breda 2026 Sport Harness",
        amountCents: 3400,
        price: "EUR 34,00",
        isDiscounted: false,
        shortDescription:
          "Pettorina sportiva coordinata Breda 2026, sviluppata per attività, iniziative di squadra e presenza sul campo.",
        fullDescription: [
          "Breda 2026 Sport Harness è una pettorina coordinata alla linea ufficiale, pensata per attività sportive e iniziative di squadra.",
          "La costruzione visiva mette in primo piano l'identità Breda 2026 e la rende adatta a contesti operativi, promozionali e community.",
          "Può essere abbinata agli altri accessori della collezione per creare un kit sportivo completo e riconoscibile.",
        ],
        imageSrc: "/Breda2026_Merch/Harness.png",
        imageAlt: "Pettorina sportiva Breda 2026",
      },
      {
        id: "SP04",
        slug: "breda-2026-lanyard",
        category: "Accessori",
        name: "Breda 2026 Lanyard",
        amountCents: 1200,
        price: "EUR 12,00",
        isDiscounted: true,
        shortDescription:
          "Lanyard ufficiale per pass, accrediti e badge, pensato per staff, ospiti e pubblico degli eventi Breda 2026.",
        fullDescription: [
          "Breda 2026 Lanyard è l'accessorio ufficiale dedicato a pass, badge e accrediti durante competizioni ed eventi.",
          "Il formato essenziale valorizza l'identità della manifestazione e garantisce coerenza visiva tra staff, partner e ospiti.",
          "È una referenza adatta anche a welcome kit, pacchetti hospitality e attività di community engagement.",
        ],
        imageSrc: "/Breda2026_Merch/Lanyard.png",
        imageAlt: "Lanyard ufficiale Breda 2026",
      },
      {
        id: "SP05",
        slug: "breda-2026-leo-mascot",
        category: "Mascotte",
        name: "Leo Mascot",
        amountCents: 2900,
        price: "EUR 29,00",
        isDiscounted: false,
        shortDescription:
          "La mascotte Leo in versione merchandising, creata per supporter, famiglie e collezionisti Breda 2026.",
        fullDescription: [
          "Leo Mascot porta il personaggio simbolo di Breda 2026 fuori dal campo e dentro la collezione ufficiale.",
          "La referenza è pensata per il pubblico più giovane, per le famiglie e per chi desidera conservare un ricordo riconoscibile dell'evento.",
          "Leo è ideale per fan zone, gifting, iniziative academy e attività di coinvolgimento della community.",
        ],
        imageSrc: "/Breda2026_Merch/Leo.png",
        imageAlt: "Mascotte Leo Breda 2026",
      },
      {
        id: "SP06",
        slug: "breda-2026-leon-cino-mascot-duo",
        category: "Mascotte",
        name: "Leon & Cino Mascot Duo",
        amountCents: 4900,
        price: "EUR 49,00",
        isDiscounted: true,
        shortDescription:
          "Il duo di mascotte Leon & Cino riunito in un set dedicato ai fan e alla community Breda 2026.",
        fullDescription: [
          "Leon & Cino Mascot Duo riunisce due protagonisti dell'universo Breda 2026 in un'unica proposta da collezione.",
          "Il set è pensato per fan, famiglie e attività promozionali che vogliono raccontare lo spirito più coinvolgente dell'evento.",
          "La coppia si presta a gifting, fan experience e contenuti dedicati alla community sportiva.",
        ],
        imageSrc: "/Breda2026_Merch/Leon&Cino.png",
        imageAlt: "Mascotte Leon e Cino Breda 2026",
      },
      {
        id: "SP07",
        slug: "breda-2026-team-pochette",
        category: "Accessori",
        name: "Breda 2026 Team Pochette",
        amountCents: 2400,
        price: "EUR 24,00",
        isDiscounted: false,
        shortDescription:
          "Pochette compatta della linea ufficiale, utile per organizzare piccoli accessori durante allenamenti e trasferte.",
        fullDescription: [
          "Breda 2026 Team Pochette è una soluzione compatta per tenere ordinati gli accessori essenziali durante allenamenti, eventi e viaggi.",
          "Il design coordinato alla collezione consente di abbinarla facilmente allo zaino e agli altri articoli ufficiali.",
          "È pensata per team kit, uso quotidiano e gifting sportivo con un formato pratico e riconoscibile.",
        ],
        imageSrc: "/Breda2026_Merch/Pochette.png",
        imageAlt: "Pochette ufficiale Breda 2026",
      },
      {
        id: "SP08",
        slug: "breda-2026-official-polo",
        category: "Abbigliamento",
        name: "Breda 2026 Official Polo",
        amountCents: 4200,
        price: "EUR 42,00",
        isDiscounted: false,
        shortDescription:
          "Polo ufficiale Breda 2026 per staff, team e supporter, con immagine coordinata e vocazione sport-lifestyle.",
        fullDescription: [
          "Breda 2026 Official Polo è il capo rappresentativo della collezione, pensato per staff, team e supporter.",
          "La linea unisce presenza sportiva e utilizzo lifestyle, mantenendo il brand dell'evento ben visibile in ogni contesto.",
          "È adatta a match day, hospitality, attività corporate e kit ufficiali coordinati.",
        ],
        imageSrc: "/Breda2026_Merch/Polo.png",
        imageAlt: "Polo ufficiale Breda 2026",
      },
      {
        id: "SP09",
        slug: "breda-2026-match-shorts",
        category: "Abbigliamento",
        name: "Breda 2026 Match Shorts",
        amountCents: 3600,
        price: "EUR 36,00",
        isDiscounted: true,
        shortDescription:
          "Shorts sportivi della collezione Breda 2026, pensati per completare il kit ufficiale dentro e fuori dal campo.",
        fullDescription: [
          "Breda 2026 Match Shorts completano la linea apparel ufficiale con una proposta dedicata ad attività e tempo libero.",
          "Il design coordinato consente di abbinarli alla polo e agli accessori della collezione per un look uniforme.",
          "Sono pensati per team kit, sessioni sportive, eventi e merchandising dedicato ai supporter.",
        ],
        imageSrc: "/Breda2026_Merch/Shorts.png",
        imageAlt: "Shorts ufficiali Breda 2026",
      },
    ],
  },
  en: {
    allProductsLabel: "All",
    discountsLabel: "Discounts",
    resultsLabel: "products",
    emptyLabel: "No products are available for this filter.",
    addToCartLabel: "Add to cart",
    addedToCartLabel: "Added to cart",
    openProductLabel: "Open product",
    backToStoreLabel: "Back to store",
    detailLabel: "Full description",
    cartTitle: "Cart",
    emptyCartLabel: "Your cart is empty.",
    checkoutLabel: "Proceed to payment",
    quantityLabel: "Qty",
    totalLabel: "Total",
    cartAriaLabel: "Open cart",
    removeFromCartLabel: "Remove",
    checkoutTitle: "Checkout",
    checkoutEmptyLabel: "Add products to the cart to continue.",
    sortLabel: "Sort by",
    filterLabel: "Filter by",
    sortOptions: {
      priceAsc: "Price low to high",
      priceDesc: "Price high to low",
      nameAsc: "Name A-Z",
    },
    categories: ["Apparel", "Accessories", "Equipment", "Mascots"],
    products: [
      {
        id: "SP01",
        slug: "breda-2026-team-backpack",
        category: "Accessories",
        name: "Breda 2026 Team Backpack",
        amountCents: 6400,
        price: "EUR 64.00",
        isDiscounted: false,
        shortDescription:
          "The official Breda 2026 backpack for training, travel and everyday use, with a coordinated visual identity.",
        fullDescription: [
          "Breda 2026 Team Backpack is the official sports collection backpack, designed to accompany athletes and supporters from the field to travel and leisure.",
          "The format is built to organize training essentials while maintaining a clean, immediately recognizable visual presence.",
          "Its coordinated Breda 2026 graphics make it suitable for team kits, promotional activities and sports gifting.",
        ],
        imageSrc: "/Breda2026_Merch/BackPack.png",
        imageAlt: "Official Breda 2026 backpack",
      },
      {
        id: "SP02",
        slug: "breda-2026-team-cap",
        category: "Accessories",
        name: "Breda 2026 Team Cap",
        amountCents: 2800,
        price: "EUR 28.00",
        isDiscounted: true,
        shortDescription:
          "The official Breda 2026 collection cap, ideal for events, match days and outdoor activities.",
        fullDescription: [
          "Breda 2026 Team Cap completes the official collection look with a lightweight, versatile accessory.",
          "It is designed for supporters, staff and teams during events, sports days and informal moments.",
          "The coordinated design makes it an immediate choice for merchandising, fan engagement and event kits.",
        ],
        imageSrc: "/Breda2026_Merch/Cap.png",
        imageAlt: "Official Breda 2026 cap",
      },
      {
        id: "SP03",
        slug: "breda-2026-sport-harness",
        category: "Equipment",
        name: "Breda 2026 Sport Harness",
        amountCents: 3400,
        price: "EUR 34.00",
        isDiscounted: false,
        shortDescription:
          "A coordinated Breda 2026 sports harness developed for activities, team initiatives and on-field presence.",
        fullDescription: [
          "Breda 2026 Sport Harness is coordinated with the official line and designed for sports activities and team initiatives.",
          "Its visual construction foregrounds the Breda 2026 identity across operational, promotional and community contexts.",
          "It can be paired with the collection's other accessories to create a complete, recognizable sports kit.",
        ],
        imageSrc: "/Breda2026_Merch/Harness.png",
        imageAlt: "Breda 2026 sports harness",
      },
      {
        id: "SP04",
        slug: "breda-2026-lanyard",
        category: "Accessories",
        name: "Breda 2026 Lanyard",
        amountCents: 1200,
        price: "EUR 12.00",
        isDiscounted: true,
        shortDescription:
          "The official lanyard for passes, accreditations and badges, designed for Breda 2026 staff, guests and audiences.",
        fullDescription: [
          "Breda 2026 Lanyard is the official accessory for passes, badges and accreditations during competitions and events.",
          "Its essential format highlights the event identity and creates visual consistency across staff, partners and guests.",
          "It also fits welcome kits, hospitality packages and community engagement activities.",
        ],
        imageSrc: "/Breda2026_Merch/Lanyard.png",
        imageAlt: "Official Breda 2026 lanyard",
      },
      {
        id: "SP05",
        slug: "breda-2026-leo-mascot",
        category: "Mascots",
        name: "Leo Mascot",
        amountCents: 2900,
        price: "EUR 29.00",
        isDiscounted: false,
        shortDescription:
          "The Leo mascot as an official merchandise item for Breda 2026 supporters, families and collectors.",
        fullDescription: [
          "Leo Mascot brings the Breda 2026 signature character beyond the field and into the official collection.",
          "The item is designed for younger audiences, families and anyone looking for a recognizable event keepsake.",
          "Leo is ideal for fan zones, gifting, academy initiatives and community engagement activities.",
        ],
        imageSrc: "/Breda2026_Merch/Leo.png",
        imageAlt: "Breda 2026 Leo mascot",
      },
      {
        id: "SP06",
        slug: "breda-2026-leon-cino-mascot-duo",
        category: "Mascots",
        name: "Leon & Cino Mascot Duo",
        amountCents: 4900,
        price: "EUR 49.00",
        isDiscounted: true,
        shortDescription:
          "The Leon & Cino mascot duo brought together in a set dedicated to Breda 2026 fans and community.",
        fullDescription: [
          "Leon & Cino Mascot Duo brings two Breda 2026 characters together in one collectible proposal.",
          "The set is designed for fans, families and promotional activities that express the event's most engaging spirit.",
          "The duo works naturally across gifting, fan experiences and sports community content.",
        ],
        imageSrc: "/Breda2026_Merch/Leon&Cino.png",
        imageAlt: "Breda 2026 Leon and Cino mascots",
      },
      {
        id: "SP07",
        slug: "breda-2026-team-pochette",
        category: "Accessories",
        name: "Breda 2026 Team Pochette",
        amountCents: 2400,
        price: "EUR 24.00",
        isDiscounted: false,
        shortDescription:
          "A compact official-line pouch for organizing small accessories during training sessions and travel.",
        fullDescription: [
          "Breda 2026 Team Pochette is a compact solution for keeping essential accessories organized during training, events and travel.",
          "Its coordinated collection design makes it easy to pair with the backpack and other official items.",
          "It is designed for team kits, everyday use and sports gifting in a practical, recognizable format.",
        ],
        imageSrc: "/Breda2026_Merch/Pochette.png",
        imageAlt: "Official Breda 2026 pochette",
      },
      {
        id: "SP08",
        slug: "breda-2026-official-polo",
        category: "Apparel",
        name: "Breda 2026 Official Polo",
        amountCents: 4200,
        price: "EUR 42.00",
        isDiscounted: false,
        shortDescription:
          "The official Breda 2026 polo for staff, teams and supporters, combining coordinated identity with sports-lifestyle appeal.",
        fullDescription: [
          "Breda 2026 Official Polo is the collection's representative garment, designed for staff, teams and supporters.",
          "The line combines sports presence and lifestyle use while keeping the event brand clearly visible in every setting.",
          "It fits match days, hospitality, corporate activities and coordinated official kits.",
        ],
        imageSrc: "/Breda2026_Merch/Polo.png",
        imageAlt: "Official Breda 2026 polo",
      },
      {
        id: "SP09",
        slug: "breda-2026-match-shorts",
        category: "Apparel",
        name: "Breda 2026 Match Shorts",
        amountCents: 3600,
        price: "EUR 36.00",
        isDiscounted: true,
        shortDescription:
          "Sports shorts from the Breda 2026 collection, designed to complete the official kit on and off the field.",
        fullDescription: [
          "Breda 2026 Match Shorts complete the official apparel line with an item dedicated to activity and leisure.",
          "The coordinated design pairs naturally with the polo and collection accessories for a consistent look.",
          "They are designed for team kits, sports sessions, events and supporter merchandise.",
        ],
        imageSrc: "/Breda2026_Merch/Shorts.png",
        imageAlt: "Official Breda 2026 shorts",
      },
    ],
  },
};

export function getStoreProduct(lang: "it" | "en", slug: string) {
  return storePageContent[lang].products.find(
    (product) => product.slug === slug
  );
}
